[package]
name = "pkgmgr-info"
version = "1.0.2"
edition = "2024"
license = "MIT"
repository = "https://github.com/SzilvasiPeter/pkgmgr-info"
description = "Reports the system package manager information"
readme = "README.md"
keywords = ["package-manager", "system-info", "platform-detection", "std-only"]
categories = ["command-line-utilities"]

[dependencies]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "deny"
pedantic = "deny"
nursery = "deny"
cargo = "deny"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[[bin]]
name = "pkgmgrinfo"
path = "src/main.rs"
